# Generated by Django 3.2.9 on 2021-12-04 17:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_time', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_center.driver')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_center.hotel')),
            ],
        ),
    ]
