# Generated by Django 3.2.9 on 2021-12-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_center', '0002_auto_20211204_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_time']},
        ),
    ]
