# Generated by Django 3.2.9 on 2021-12-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_center', '0003_alter_trip_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='trips',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='trips',
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_center.driver'),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_center.hotel'),
        ),
    ]
