# Generated by Django 3.2.9 on 2021-12-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_center', '0004_auto_20211205_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
