# Generated by Django 3.2.9 on 2021-12-05 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_center', '0005_delete_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_time', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_center.driver')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_center.hotel')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
